---
title: "Image2023"
---

This is a Quarto website.

All submissions to the Image23 conference with additional figures, references, ...


List of abstracts:
   
- [Learned one-shot imaging](OneShot/abstract.qmd) Learned non-linear simultenous source and corresponding supershot for seismic imaging.

- [Sequential Bayesian Inference](SequentialBayes/abstract.qmd)  Plume Monitoring with Learned Sequential Bayesian Inference

- [Coupled physics inversion](yin2023IMAGEend2end/abstract.qmd) Coupled physics inversion for geological carbon storage monitoring.

- [Bayesian FWI](BayesianFWI/abstract.qmd) Amortized Bayesian Full Waveform Inversion and Experimental Design with Normalizing Flows

- [Bayesian Kriging](BayesianFWI/abstract.qmd) Generative Seismic Kriging with Normalizing Flows

- [Detectability with Vision Classification](DetectabilityWithVision/abstract.qmd) Analysis of CO2 Leakage Detectability via Vision Classifier
- [3D survey design](zhang2023IMAGEsg/abstract.qmd) 3D seismic survey design by maximizing the spectral gap

These abstracts are released under the Creative Commons License type [BY]. Copyrights (c) [SLIM Group], Georgia Institute of Technology

[BY]:https://creativecommons.org/licenses/by/4.0/
[SLIM Group]:https://slim.gatech.edu
