---
title: "Monitoring Subsurface CO~2~ Plume with Sequential Bayesian Inference"
author:
  - name: Ting-Ying Yu
    affiliations:
      name: Georgia Institute of Technology
  - name: Rafael Orozco
    affiliations:
      name: Georgia Institute of Technology
  - name: Ziyi Yin
    affiliations:
      name: Georgia Institute of Technology
  - name: Mathias Louboutin
    affiliations:
      name: Georgia Institute of Technology
  - name: Felix J. Herrmann
    affiliations:
      name: Georgia Institute of Technology
description: | 
  empty
bibliography: abstract.bib
abstract: |
  empty
---

::: hidden
$$
    \newcommand{\pluseq}{\mathrel{+}=}
$$
:::

# Image 2023 abstract

## OBJECTIVES AND SCOPE (667/600 characters)
To monitor and predict the CO~2~ dynamics for geological carbon storage, reservoir engineers usually perform fluid-flow simulations using the existing Earth subsurface profiles. However, without considering the stochasticity caused by the constantly changing Earth subsurface and the injection process, CO~2~ plume predictions can be wrong. We demonstrate a framework using sequential Bayesian inference to simulate the time-evolving CO~2~ plume with the stochasticity induced by the varying injection rate. By conditioning the CO~2~ plume predictions on seismic observations, we show a more accurate prediction of the CO~2~ plume with the uncertainty characterized.

## METHODS, PROCEDURES, PROCESS (1855/1500 characters)
We generate the prior x_0, a dataset with 128 CO~2~ saturation data (x) each with a size of 64x64 . Each prior data has a circular initial CO~2~ plume with a uniformed CO~2~ saturation s \sim N(0.2,0.8). Besides the prior, two physics models, the transition model (M) and seismic observation model (H), are used for all experiments. The stochastic transition model to calculate the evolution of CO~2~ saturation data over each timestep with fluid flow physics with a randomized injection rate I \sim N(0,0.2). The seismic model made observations (y) based on the simulated acoustic measurements at the surface. 

The ground truth is generated by randomly sampling one CO~2~ saturation data (x^*) from the prior and transition over five timesteps. Seismic observations (\mathbf{y}^*) are made at each timestep. Two numerical experiments are performed to predict the ground truth: unconditioned simulation and seismic-conditioned simulation. 

The unconditioned simulation is performed to represent the current CO~2~ plume forecasting technique. The entire prior dataset is transitioned and seismically observed for five timesteps.

Our seismic-conditioned simulation involves four main processes: transitioning, seismic observation, Conditional Normalizing Flow (CNF) training, and posterior sampling (Figure 1). After the prior (x_{n}) is transitioned and seismically observed, the (x_{n+1},y_{n+1}) are the training pair  for Conditional Normalizing Flow, a generative network that can learn to sample from conditional distributions p(x|y). Therefore, we sample from the conditioned CNF-generated posterior on the round truth observation x_{n+1} \sim p(x|y=y_{n+1}^*. For sequential Bayesian inference, the posterior samples are served as the prior of the next timestep, so \mathbf{x}_{n+1} \sim p(x|y=y_{n+1}^*)) is transitioned to x_{n+2}. 

## RESULTS, OBSERVATIONS, CONCLUSIONS (1073/1500 characters)
CO~2~ plume predictions are made using both conditioned seismic and unconditioned simulations. The seismic-conditioned predictions are the conditional mean of the posterior samples, while the unconditioned predictions are the ensemble mean at each timestep. Figure 2 shows that seismic-conditioned predictions are more accurate in predicting the ground truth and have a smaller conditional sample variance than the unconditioned ensemble mean predictions. 

The uncertainties can be characterized by examining the difference between the ground truth and predictions. For the seismic-conditioned predictions, the uncertainties are located near the injection well. The boundary of the plume is well-predicted by the seismic-conditioned method while the unconditioned simulation has an increasing uncertainty at the boundary over time. 

Overall, we conclude that the unconditioned simulation poorly predicts the CO~2~ plume. Our seismic-conditioned framework assimilates information and learns over time, which improves the CO~2~ forecasting and characterizes uncertainties. 

## SIGNIFICANCE/NOVELTY (238/600 characters)
To our understanding, the seismic-conditioned framework is the first geological carbon storage monitoring model that assimilates information with seismic observations, updates the CO~2~ plume predictions, and characterizes uncertainties. 